### PR TITLE
Add motion source

### PR DESCRIPTION
**Pull request by wilsonbow**

### CODE REVIEW

**Comment by lindsaymarkward** [comment]
Can you add some comments/details here please @wilsonbow ?

**Comment by wilsonbow** [comment]
This is code for an Arduino motion sensor which is compatible with the dataflow server. I have been working on this project with @ozyjay.

**Comment by adamrehn** [comment]
Cool, thanks for the contribution Wilson, I didn't realise anyone was still using this old thing! Could you please add a corresponding entry in the file `server/nodes/sources.json` so that the server can utilise this new source node?

**Comment by wilsonbow** [comment]
Hey Adam. Jason and I have been working on "Stage 2" of this project. The goal is to have a simulated smart home for open day.

**Comment by adamrehn** [comment]
Cool, sounds good!

**Pull request merged**
